PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cnluwv: <https://linkeddata.competentnl.nl/def/cnluwv#>

# Laat alles zien rondom <https://linkeddata.competentnl.nl/id/beroep/R1000000258>

DESCRIBE <https://linkeddata.competentnl.nl/id/beroep/R1000000258>
