PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cnluwv: <https://linkeddata.competentnl.nl/def/cnluwv#>

# voeg de volgende triple toe: <ik> <zeg> “hello world” ;

INSERT DATA {
	<ik> <zeg> "hello world" .
}
